import BaseSeeder from '@ioc:Adonis/Lucid/Seeder';
import Exam from 'App/Models/Exam';
import Subgroup from 'App/Models/Subgroup';

export default class extends BaseSeeder {
  BASE = [
    {
      subgroup: 'Exames em Geral',
      name: '17-Hidroxi Progesterona',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Ácido Fólico',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Albumina',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'ALT (TGP)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Amilase',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Amônia',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Análise com citologia de efusão',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Análise com citologia de efusão - PLANTÃO',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Análise de cálculo  uninário',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Análise de cálculo vesical urinário (cristalográfica)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Análise de efusão(proteína total +contagem de células)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Análise de efusão(proteína total +contagem de células) - PLANTÃO',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Análise de LCR',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Análise de LCR - PLANTÃO',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Análise medula óssea (mielograma) + hemograma',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Antifungigrama (inclusão)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'AST (Aspartato Aminotransferase)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Bacteriológico direto',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Bilirrubina Total',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Bilirrubina Total e frações',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Biópsia pele (dermatopatia)  DualPath para Werner',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Biópsia simples + avaliação de margem cirúrgica + pesquisa metástase em linfonodo',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Cálcio total',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Cálcio total - PLANTÃO',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Campo escuro',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'CEA - Tecsa',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Check-up 1 (básico 2 +Urinálise)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Check-up 1 (básico 2 +Urinálise) - PLANTÃO',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Check-up 2  felino (básico 2 + GGT)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Check-up 2  felino (básico 2 + GGT) - PLANTÃO',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Check-up 3 (básico 2 +Urinálise +trigl+colest+bilirrub+cálcio)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Check-up 3 (básico 2 +Urinálise +trigl+colest+bilirrub+cálcio) - PLANTÃO',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'check-up 4 (check-up 3+ íons)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Check-up 5 (check-up 4 + T4)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Check-up comp (básico 2 +Urinálise +trigl+colest+bilirrub+cálcio+ast+potás+sódio+cl+fos+CK+TP+TTPA))',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Citologia 1 lesão - até 4 Laminas',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Citologia 2 lesões - até 8 lâminas',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Citologia Vetpat',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Citometria de fluxo (Vetpat)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'CK-NAC (creatininaquinase)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Coagulopatia (Hemograma completo+TP+TTPA+Pesquisa de hematozoário)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Colesterol',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Colesterol + Frações (Colesterol Total+LDL+VLDL+HDL)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Coloração Gram',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Coloração Gram - PLANTÃO',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Coloração Panótico - 4 lâminas',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Contagem de Plaquetas',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Contagem de Plaquetas - PLANTÃO',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Coprocultura + antibiograma',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Coproparasitologico (Faust+willis+hoffman)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Cortisol Basal',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Creatinina',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Creatinina - PLANTÃO',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Creatinina Urinária',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Creatinina urinária - PLANTÃO',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Cultura anaeróbios (sem antibiograma)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Cultura com Antibiograma Anaeróbios',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Cultura de feridas e fragmentos de tecidos + antibiograma MIC',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Cultura fúngica + antifungigrama',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Cultura Fúngica - DualPath',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Cultura fúngica - Provet',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Cultura Fúngica - Tecsa',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Dessorar',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Diabetes 1 (básico 2+urinálise+frutosamina)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Diabetes 1 (básico 2+urinálise+frutosamina) - PLANTÃO',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Dosagem de amônia',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Dosagem de Brometo de Potásio Sérico',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Dosagem de Insulina Sérica',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Dosagem de Progesterona',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Dosagem Sérica Fenobarbital',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Eletroforese de proteinas',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Eletroforese de proteínas (soro)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Eletrólitos(Hemograma completo+Lactato+Potássio+Cloro+Sódio+Cálcio total)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'FA (Fosfatase Alcalina)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Fator antinúcleo - FAN',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Fator reumatóide - FAN',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Ferro Sérico',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Fibrinogênio',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Fósforo',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Frutosamina',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Gasometria',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Gasometria - PLANTÃO',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'GGT',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Giárdia - Elisa fezes',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Hematócrito',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Hematócrito - PLANTÃO',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Hemocultura + antibiograma MIC',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Hemograma Completo',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Hemograma Completo - PLANTAO',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Histopatologico  ( 2 lesões - mesma suspeita)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Histopatologico  ( 2 lesões - suspeitas distintas)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Histopatológico (1 frag) com avaliação de margem cirúrgica ( 1 amostra)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Histopatológico (VetPat)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Histopatológico + pesquisa de metástase em linfonodo',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Histopatológico Cadeia Mamária (3nódulos) + pesquisa de metástase em linfonodos',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Histopatológico Cadeia Mamária (até 3 nódulos)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Histopatológico Cadeia Mamária + avaliação  de margens',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Histopatologico cadeia mamária com avaliação de margens (3nódulos)+pesq metástase em linfonodos',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Histopatológico dermatopatia ( até 3 pontos distintos)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Histopatológico Peça cirúrgica ( Baço, amputação, peças grandes)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Histopatologico Simples (1 Amostra)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Identificação bacteriana',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Imunoistoquímica (Vetpat)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Íons (Potássio+Cloro+Cálcio total + Sódio)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Íons (Potássio+Cloro+Cálcio total + Sódio) - PLANTÃO',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Lactato',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Lactato - PLANTÃO',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Leucograma',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Magnésio',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Micologico Direto',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Micológico direto+bacteriológico direto+pesquisa de ácaros',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Mutação genética do BRAF - Vetpat',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Necrópsia acima de 15kg',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Necrópsia até 15kg',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Necrópsia cosmética acima de 15kg',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Necrópsia cosmética até 15kg',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Necrópsia pericial acima de 15kg',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Necrópsia pericial até 15kg',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Oncomapa (Vetpat)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Otocultura + antibiograma MIC',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Pacote prognóstico mastocitoma (PCR+imunoistoquímica) Vetpat',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Painel FELV Plus (RNA e DNA) - PCR Qualitativo',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Papa Hemacias',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Papa Hemacias (Plantão)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'PARR (Vetpat)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'PCR  Cinomose PETSCOP',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'PCR Babesia PETSCOP',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'PCR Cinomose - Quantitativo',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'PCR Ehrlichia PETSCOP',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'PCR Erlichia Spp - Qualitativo',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Pcr Hemoparasita Combo (Erlichia, babesia e Anaplasma)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'PCR Leishmaniose spp - Quantitativo',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'PCR Leptospira Sp',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'PCR para oncogene C-kit em mastocitoma (Vetpat)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'PCR PIF quantitativo',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'PCR plus - Vetpat',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Perfil alérgenos ambientais e ambiental',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Perfil Básico 1 (hemograma completo+creatinina + ALT)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Perfil Básico 1 (hemograma completo+creatinina + ALT) -  PLANTÃO',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Perfil Básico 2  (hemograma completo+creatinina+Uréia+ ALT +FA+Albumina+PT)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Perfil Básico 2 (hemograma completo+creatinina+Uréia+ ALT +FA+Albumina+PT) - PLANTÃO',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Perfil Cardíaco (hemog+ALT+creat+potássio+cloro+sódio)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Perfil Coagulopatia (hemog+TP+TTPA+pesq hematoz)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Perfil diabético ( Hemograma completo+creat+uréia+ALT+FA+Albumina+PT+Urinálise+Frutosamina)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Perfil Filhote (hemograma completo +pesq hematozoários+Cinomose(Ag)+Parvovirose(Ag)+Coronavirose(Ag)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Perfil hemodiálise(renal acomp+potassio+cloro+sodio)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Perfil hemodiálise(renal acomp+potassio+cloro+sodio) - PLANTÃO',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Perfil hepático (hemog +ALT+FA+GGT+Alb+Ureia+bilirrubinas) PLANTÃO',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Perfil hepático (hemog +ALT+FA+GGT+Alb+Ureia+creat+bilirrubinas)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Perfil hepático 2 (hepático 1 + creat+trigl+colest+TP+TTPA)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Perfil hepático 2 (hepático 1 + creat+trigl+colest+TP+TTPA) - PLANTÃO',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Perfil obesidade 2 (basico2+colest+triglic+urinalise+t4)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Perfil Obesidade 3 (hemo+creat+ALT+FA+colest+triglec+ureia)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Perfil Obesidade(hemog+creat+ALT+FA+Colest+trigl+urinálise)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Perfil Pancreático ( SNAP lipase+triglic+colest+FA)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Perfil Pré-cirúrgico básico (Hemograma completo+Creat+ALT+TP+TTPA)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Perfil Pré-cirúrgico básico (Hemograma completo+Creat+ALT+TP+TTPA) - PLANTÃO',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Perfil Pré-cirúrgico completo (Hemograma completo+Creat+Uréia+ALT+FA+ALbumina+PT+TP+TTPA)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Perfil Pré-cirúrgico completo (Hemograma completo+Creat+Uréia+ALT+FA+ALbumina+PT+TP+TTPA)- PLANTÃO',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Perfil Renal 1 (hemog+creat+ureia+alb+urinálise)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Perfil Renal 1 (hemog+creat+ureia+alb+urinálise)- PLANTÃO',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Perfil Renal 2 (renal 1+ proteína:creat urinária + Fosf)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Perfil Renal 2 (renal 1+ proteína:creat urinária + Fosf) - PLANTÃO',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Perfil Renal 3(hemog+creat+uréia+alb+urinálise+SDMA)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Perfil renal acompanhamento (hemog + creat+ureia)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Perfil renal acompanhamento (hemog + creat+ureia) - PLANTÃO',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Perfil Sanguíneo básico NAV - PLANTÃO',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Pesquisa células LE',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Pesquisa Corpusculo de Lentz(Cinomose)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Pesquisa de ácaros',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Pesquisa de anticorpo  antinuclear',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Pesquisa de Hemotozoários',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Pesquisa de Mycoplasma haemofelis',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Plasma Fresco Congelado',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Plasma Fresco Congelado (Plantão)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Potássio + Cloro + Sódio',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Proteína plasmática total (PPT)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Reação Cruzada',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Reação Cruzada - PLANTÃO',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Reticulócitos (inclusão)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Reticulócitos - PLANTÃO',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Reticulócitos com hemograma',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Reticulócitos com hemograma - PLANTÃO',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Sangue Total',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Sangue Total (Plantão)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'SDMA (Dimetilarginina Simétrica)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Snap Test - 4Dx Plus (Erlichia/Anaplasma/Dirofilaria/Lyme - IDEXX)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Snap Test - Combo (Fiv/Felv - IDEXX)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Snap Test - Kit de Teste Antígeno Cinomose (Alere)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Snap Test - Kit de Teste Antígeno Parvovirose (Alere)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Snap Test Giardia',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Snap test Lipase',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Sorologia Brucelose Canina',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Sorologia Coronavirus Felino PIF',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Sorologia Erlichia e babesia (IGG, IGM)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Sorologia Leishmaniose diluição total (felina)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Sorologia Leishmaniose RIFI+ELISA',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Sorologia Leptospirose diluição total',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Sorologia Neospora RIFI',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Sorologia Toxoplasmose',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Suplemento - Glicose 50% Ampola 10ml Injetável',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Supressão com Baixa Dose de Dexa 0-4-8 hrs Após',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Supressão com Baixa Dose de Dexa 0-8 hrs Após',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'T3 Total quimioluscência',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'T4 Livre Por Diálise + TSH',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'T4 total',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Taxa de centrifugação',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Taxa de urgência - Citologia ( 48 horas úteis)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Taxa de urgência - exame sangue geral',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Taxa de urgência - histopatológico (4 dias úteis)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Teste alérgico com 24 alérgenos',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Teste de Autoaglutinação em Salina',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Teste de COOMBS',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Teste de Knott',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Teste Reação Alimentar Canina',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Titulação de Raiva - Tecsa',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Toxicológico 1 item',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Toxicológico 11 itens',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'TP+ TTPA - PLANTAO',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'TP+TTPA',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Transfusão de Sangue - (Bolsa DualPath)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Triagem endócrina (básico 2+GGT+colesterol+triglicerídeos)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Tricograma',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Triglicerídeos',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'UPC',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'UPC - PLANTAO',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Uréia',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Uréia - PLANTÃO',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Urinálise',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Urinálise - PLANTÃO',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Urocultura + antibiograma MIC',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'VacciCheck (teste painel vacinal; IgG parvovirose, cinomose e hepatite infecciosa canina)',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Vitamina B12',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
    {
      subgroup: 'Exames em Geral',
      name: 'Vitamina D',
      description: '',
      type: 'GERAL',
      own_laboratory: false,
    },
  ];

  public async run() {
    const subgroups = await Subgroup.all();

    await Exam.fetchOrCreateMany(
      'name',
      this.BASE.map(exam => ({
        name: exam.name,
        description: exam.description,
        type: exam.type,
        own_laboratory: exam.own_laboratory,
        subgroup_id: subgroups.find(
          subgroup => subgroup.description === exam.subgroup,
        )?.id,
      })),
    );
  }
}
