name: Deploy

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug SSH
        run: ssh -vvv -i <(echo "${{ secrets.DEV_SSH_PRIVATE_KEY }}") -p ${{ secrets.PORT }} ${{ secrets.USER }}@${{ secrets.DEV_HOST }} whoami

      - name: Deploy Application
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.FOLDER }}
            git pull origin ${{ github.ref_name }}
            yarn
            rm -rf dist
            yarn build
            cp .env build/.env
            cp -r public build/public
            export NODE_ENV=production
            node ace migration:run
            pm2 restart ${{ secrets.APP }}
            pm2 restart cron

      - name: Notify Discord
        if: always()
        run: |
          STATUS="🔴 Falhou [dev]"
          if [ "${{ job.status }}" == "success" ]; then STATUS="✅ Sucesso [dev]"; fi
          curl -H "Content-Type: application/json" -d "{\"content\": \"$STATUS - ${{ github.workflow }}\"}" \
          ${{ secrets.DEV_DISCORD_WEBHOOK }}

